// Auto-generated by vue-i18n:generate command
// Generated: 2025-09-08T06:13:18+00:00
import { createI18n } from "vue-i18n";

import en from "./en.json";
import es from "./es.json";
import fr from "./fr.json";
import zh from "./zh.json";

const messages = {
    en,
    es,
    fr,
    zh,
};

const i18n = createI18n({
    legacy: false,
    locale: "en",
    fallbackLocale: "en",
    messages,
});

export default i18n;
