// Auto-generated by vue-i18n:generate command
// Generated: 2025-12-19T07:27:37+00:00
import { createI18n } from 'vue-i18n'

import ca from './ca.json'
import en from './en.json'
import es from './es.json'
import fr from './fr.json'
import ko from './ko.json'
import zh from './zh.json'

const messages = {
    ca,
    en,
    es,
    fr,
    ko,
    zh
}

const i18n = createI18n({
    legacy: false,
    locale: 'en',
    fallbackLocale: 'en',
    messages
})

export default i18n
